### ISSUE TITLE
Backward compatibility

### ISSUE THREAD

**Issue by de-barros** [Wenchao-Ma/GDINA#1]
I installed GDINA 1.9.9.9 and tried to re-run a command that worked just fine previously: 

`mod4<-GDINA(dat = rdata_rev[,-1], verbose = 2, Q = qmatrix_rev3[,c(-1)], model = "GDINA", att.prior = struc$att.prob, att.str = TRUE, att.dist = "saturated")`

Now I get the following error. 

> Error in .Call("_GDINA_eta", PACKAGE = "GDINA", Q) : "_GDINA_eta" not available for .Call() for package "GDINA"

**Comment by Wenchao-Ma** [comment]
Thanks. Could you please attach the data and Q or email your data and Q, which produce the error, to wenchao.ma@ua.edu for a close look?

**Comment by de-barros** [comment]
Thanks and apologies. Problem solved by re-starting the R session after installation.
