### ISSUE TITLE
modelcomp after GDINA with user-specified attr. structure

### ISSUE THREAD

**Issue by de-barros** [Wenchao-Ma/GDINA#2]
A GDINA model with user-specified attribute structure runs without problems (Example 5 in `GDINA `documentation).

```
Q <- sim30GDINA$simQ
K <- ncol(Q)
# divergent structure A1->A2->A3;A1->A4->A5;A1->A4->A6
diverg <- list(c(1,2),
               c(2,3),
               c(1,4),
               c(4,5))
struc <- att.structure(diverg,K)
# data simulation
N <- 1000
true.lc <- sample(c(1:2^K),N,replace=TRUE,prob=struc$att.prob)
table(true.lc) #check the sample
true.att <- attributepattern(K)[true.lc,]
gs <- matrix(rep(0.1,2*nrow(Q)),ncol=2)
# data simulation
simD <- simGDINA(N,Q,gs.parm = gs,
                 model = "DINA",attribute = true.att)
dat <- extract(simD,"dat")
modp1 <- GDINA(dat = dat, Q = Q, att.prior = struc$att.prob, att.str = TRUE, att.dist = "saturated")
```

Thereafter, `modelcomp` gives the following errors: 

`lr <- modelcomp(mod4, method = "LR")`

> error: matrix multiplication: incompatible matrix dimensions: 2x4 and 3x1
> Error in Calc_Dj(item.parm[[j]], designMj = DesignMatrices[[j]], linkfunc = linkfunc[j]) : 
>   matrix multiplication: incompatible matrix dimensions: 2x4 and 3x1

`wald <- modelcomp(mod4, method = "Wald")`

> Error in svd(X) : infinite or missing values in 'x'

**Comment by Wenchao-Ma** [comment]
The package currently only supports the estimation of CDMs with attribute structures. Many functions that suitable for CDMs without structures may not be applicable in this case. More studies in this area may be necessary.
