### ISSUE TITLE
modelfit

### ISSUE THREAD

**Issue by jeannehsinclair** [Wenchao-Ma/GDINA#3]
Hello,

I am running GDINA and when I tried to use the `modelfit` function, I received this error:

`Error in modelfit(mod4) : could not find function "modelfit"`

I just updated the GDINA package in R. I would appreciate any help you could provide in using the `modelfit` function. Please let me know if you need further information, and thank you for your help!

**Comment by Wenchao-Ma** [comment]
Did you load the GDINA R package using library()? If yes and you still have the problem, please send me the reproducible code, and data if necessary at wenchao.ma@ua.edu
