### ISSUE TITLE
Problem with model fit

### ISSUE THREAD

**Issue by NimaRah** [Wenchao-Ma/GDINA#5]
Hello,

I use GDINA for analyzing TIMSS data. After run the `gdina` function and reach convergence, in `modelfit` function, I received this error:

```
Error in if (func.lambda(lower, X2, df, b = bb) * func.lambda(l.upper,  : 
  missing value where TRUE/FALSE needed
```

I would appreciate any help you could provide in using the `modelfit` function. Please let me know if you need further information, and thank you for your help.

**Comment by Wenchao-Ma** [comment]
Hi, you can send me your data and Q for a closer look.
