### ISSUE TITLE
Error in alpha2(K): Mat::col(): index out of bounds

### ISSUE THREAD

**Issue by themrzmaster** [Wenchao-Ma/GDINA#7]
Hi, when I try to run 
`
est <- GDINA(dat = data, Q = Q, model = "GDINA")`

with my own data, I get the following error:

Error in alpha2(K): Mat::col(): index out of bounds
Traceback:

```
1. GDINA(dat = data, Q = Q, model = "logitGDINA")
2. SG.Est(dat = dat, Q = Q, model = model, sequential = sequential, 
 .     att.dist = att.dist, att.prior = att.prior, saturated = saturated, 
 .     att.str = att.str, mono.constraint = mono.constraint, latent.var = latent.var, 
 .     verbose = verbose, catprob.parm = catprob.parm, loglinear = loglinear, 
 .     item.names = item.names, control = control, item.prior = item.prior, 
 .     nloptr_args = nloptr.args, auglag_args = auglag.args, solnp_args = solnp.args, 
 .     linkfunc = linkfunc, higher.order = higher.order, solver = solver, 
 .     DesignMatrices = design.matrix, ConstrPairs = constr.pairs)
3. as.matrix(att.structure(hierarchy.list = att.str, K = K, Q = Q, 
 .     att.prob = "uniform")$att.str)
4. att.structure(hierarchy.list = att.str, K = K, Q = Q, att.prob = "uniform")
5. attributepattern(K = K, Q = Q)
6. alpha2(K)
```

I could not find what is wrong with my data.

Any tips? thanks

**Comment by Wenchao-Ma** [comment]
Could you please send me your data, Q matrix and a piece of code that can replicate the error to ***@***.***?

Sent from my phone

________________________________
From: Lucca Zenóbio ***@***.***>
Sent: Tuesday, April 27, 2021 8:34:19 AM
To: Wenchao-Ma/GDINA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [Wenchao-Ma/GDINA] Error in alpha2(K): Mat::col(): index out of bounds (#7)


Hi, when I try to run
est <- GDINA(dat = data, Q = Q, model = "GDINA")

with my own data, I get the following error:

Error in alpha2(K): Mat::col(): index out of bounds
Traceback:

1. GDINA(dat = data, Q = Q, model = "logitGDINA")
2. SG.Est(dat = dat, Q = Q, model = model, sequential = sequential,
 .     att.dist = att.dist, att.prior = att.prior, saturated = saturated,
 .     att.str = att.str, mono.constraint = mono.constraint, latent.var = latent.var,
 .     verbose = verbose, catprob.parm = catprob.parm, loglinear = loglinear,
 .     item.names = item.names, control = control, item.prior = item.prior,
 .     nloptr_args = nloptr.args, auglag_args = auglag.args, solnp_args = solnp.args,
 .     linkfunc = linkfunc, higher.order = higher.order, solver = solver,
 .     DesignMatrices = design.matrix, ConstrPairs = constr.pairs)
3. as.matrix(att.structure(hierarchy.list = att.str, K = K, Q = Q,
 .     att.prob = "uniform")$att.str)
4. att.structure(hierarchy.list = att.str, K = K, Q = Q, att.prob = "uniform")
5. attributepattern(K = K, Q = Q)
6. alpha2(K)


I could not find what is wrong with my data.

Any tips? thanks

**Comment by themrzmaster** [comment]
for some reason your email is hidden. Can you please try again?

**Comment by Wenchao-Ma** [comment]
That’s strange. Here it is: Wenchao.ma at ua.edu

Sent from my phone

________________________________
From: Lucca Zenóbio ***@***.***>
Sent: Tuesday, April 27, 2021 8:40:25 AM
To: Wenchao-Ma/GDINA ***@***.***>
Cc: Wenchao Ma ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [Wenchao-Ma/GDINA] Error in alpha2(K): Mat::col(): index out of bounds (#7)


for some reason your email is hidden. Can you please try again?

**Comment by themrzmaster** [comment]
thanks, just sent it.

**Comment by themrzmaster** [comment]
The issue seems to be with the number of attributes. 
Shouldn't it be possible to estimate it using higher order traits? 
As I see it scales 2k instead of 2ˆk

`est <- GDINA(dat = data, Q = Q, model = "GDINA", att.dist = "higher.order", higher.order = list(model = "2PL"))`

**Comment by Wenchao-Ma** [comment]
Not really. Although the number of parameters is much fewer, you still need to have a N x 2^K matrix for the posterior.

Sent from my phone

________________________________
From: Lucca Zenóbio ***@***.***>
Sent: Tuesday, April 27, 2021 4:54:24 PM
To: Wenchao-Ma/GDINA ***@***.***>
Cc: Wenchao Ma ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [Wenchao-Ma/GDINA] Error in alpha2(K): Mat::col(): index out of bounds (#7)


The issue seems to be with the number of attributes.
Shouldn't it be possible to estimate using higher order traits?
As I see it scales 2k instead of 2ˆk

est <- GDINA(dat = data, Q = Q, model = "GDINA", att.dist = "higher.order", higher.order = list(model = "2PL"))
