### ISSUE TITLE
ACDM model between PC and Mac

### ISSUE THREAD

**Issue by krisherliu** [Wenchao-Ma/GDINA#9]
Hi. 
  Recently I used GDINA library to run some CDM models.  The summary of DINA/DINO/GDINA has no any problem. When I run ACDM model, the summary of Mac always shows some different values of LogLik/AIC/BIC/CAIC/SABIC.  Please tell me if I did anything wrong. 

```
library("GDINA")
factordata <- read.csv("factorandmultiples.csv")
factorQ <- read.csv("q-matrix.csv")

ACDMmod1 <- GDINA(dat = factordata, Q = factorQ, model = "ACDM")
summary(ACDMmod1)
```

**Comment by Wenchao-Ma** [comment]
Thank you for letting me know. I’ll take a look and get back to you!

Best,
Wenchao

Sent from my phone

________________________________
From: krisherliu ***@***.***>
Sent: Thursday, December 22, 2022 9:20:25 AM
To: Wenchao-Ma/GDINA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [Wenchao-Ma/GDINA] ACDM model between PC and Mac (Issue #9)


Hi.
Recently I used GDINA library to run some CDM models. The summary of DINA/DINO/GDINA has no any problem. When I run ACDM model, the summary of Mac always shows some different values of LogLik/AIC/BIC/CAIC/SABIC. Please tell me if I did anything wrong.

library("GDINA")
factordata <- read.csv("factorandmultiples.csv")
factorQ <- read.csv("q-matrix.csv")

ACDMmod1 <- GDINA(dat = factordata, Q = factorQ, model = "ACDM")
summary(ACDMmod1)

**Comment by Wenchao-Ma** [comment]
Hi, I compared the results using ACDM based on data and Q in sim10GDINA on Mac and Windows but didn't see any differences. you can send me your data and Q for a closer look, if necessary.

**Comment by krisherliu** [comment]
> 
hi, I attatched some sample .csv files for reference.

factorandmultiples.csv:
https://drive.google.com/file/d/1bK1BdhBSzwrUusk71s9qF4KKxRGkO4X0/view?usp=sharing

q-matrix:
https://drive.google.com/file/d/1bHa-rxe4JWeco-zXDyi2M6aus4pwxbB9/view?usp=sharing


code is as mentioned above:
`library("GDINA")
factordata <- read.csv("factorandmultiples.csv")
factorQ <- read.csv("q-matrix.csv")

ACDMmod1 <- GDINA(dat = factordata, Q = factorQ, model = "ACDM")
summary(ACDMmod1)`
